export const ITEM_ADD = 'TASK_ADD';
export const ITEM_CHANGE_IMPORTANCE = 'ITEM_CHANGE_IMPORTANCE';
export const ITEM_CHANGE_IMPORTANCE = 'ITEM_CHANGE_ISDONE';
export const ITEM_REMOVE = 'ITEM_REMOVE';